server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/china_union?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone = Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
