server:
  port: 11111
spring:
  application:
    name: seata-cloud-user
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
seata:
  tx-service-group: my_test_tx_group
feign:
  hystrix:
    enabled: true
