server:
  port: 6077
spring:
  datasource:
    url: jdbc:mysql://localhost:8066/TESTDB
    username: xiaofeng
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: spring-boot-mycat

