server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://10.9.101.28:3306/hubei-yichang-park?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone = Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: hubei-yichang-park
    password: 8vuj74lpX7Rf