server:
  port: 2222
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/china_union?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-boot-mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #print sql to console
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl