server:
  port: 2222
spring:
  datasource:
    url: jdbc:mysql://10.253.103.110:3306/vie_cloud?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: t_a_vie_cloud
    password: 9ydGVkIjpmYW
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-boot-mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #print sql to console
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl