server:
  port: 10086
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xiaofeng
    password: 123456
    virtual-host: /xiaofeng
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  data:
    mongodb:
      uri: mongodb://tianxiaofeng:Iyunbao666@localhost:27017/user

